### PR TITLE
remove empty ToolTipMenuTest release target to fix ios release builds

### PR DESCRIPTION
**Pull request by johakr**
If you try to build a production release of an iOS app it will fail for the ToolTipMenuTest release target due to signing issues. Hence, i removed the (empty) ToolTipMenuTest.

### CODE REVIEW

**Comment by chirag04** [comment]
i'm fine with this. alternative would be to fix signing issue on that target. will let @enahum decide.

**Comment by enahum** [comment]
Im ok with this as well, but so far I’ve been able to build my apps in production without any issues.

Do you mind and share the specific issues that you are facing?

**Comment by johakr** [comment]
@enahum @chirag04 I'm really not an expert regarding singing issues / configuration. Might be a configuration issue on my side. But never had this issue with any other react-native library.

`=== BUILD TARGET ToolTipMenuTests OF PROJECT ToolTipMenu WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Signing for "ToolTipMenuTests" requires a development team. Select a development team in the project editor.
Code Signing Error: Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 11.2'

** ARCHIVE FAILED **`

**Comment by Kelvne** [comment]
We're facing this problem while building on our CI platform and looking for solutions.

**Pull request merged**
