### PR TITLE
Integrate js api changes from taskrabbit

### PR DESCRIPTION
**Pull request by ghost**
- Tooltip can now be applied to any child element passed by the caller, not hardcoded to <Text> only.
- Abstracted the logic used to show the tooltip from the caller. The caller can now simply pass in a list of actions to be displayed on press or long press, as specified.
- Preserved a global callback (onActionSelected) which accepts the command string that was selected.
- Kept ES5 syntax for the most part. Some things such as the ES6 export default make it a bit harder to consume the component from ES5.

### CODE REVIEW

**Comment by chirag04** [comment]
@jrichardlai thoughts?

@sevachb @jrichardlai I can add you guys as collabs if interested

**Comment by jrichardlai** [comment]
Oops! forgot about it imma make a PR for tonight!

**Comment by chirag04** [comment]
awesome. Let's merge the two codebases.

**Comment by jrichardlai** [comment]
Oops didn't see this was a PR, well this PR will remove the previous usage of ToolTipText, I was planning on keeping the previous Api, but this is fine if you think its okay.

**Comment by chirag04** [comment]
I thought your fork removes the usage of ToolTipText. isn't it?

**Comment by jrichardlai** [comment]
It does, and I think its better if we only keep one usage, but its up to you. I'm making a PR now. let you comment over there :).

**Comment by ghost** [comment]
Hey guys, so I basically brought back jrichardlai's change here with 2 small changes (described above).
1. Stuck with ES5 for the most part
2. Preserved a global callback

Can we accept this PR as a starting point? It's all good to go.

**Comment by chirag04** [comment]
@sevachb Thanks for putting it all together. I think we all should agree on api once and just ship it once rather than doing it twice.

**Comment by ghost** [comment]
Sure thing. What are the things in the current PR that you have in mind?

**Comment by chirag04** [comment]
@sevachb https://github.com/chirag04/react-native-tooltip/pull/8 just landed on master.

**Pull request closed without merging**
